load("@rules_zig//zig:defs.bzl", "zig_binary")

zig_binary(
    name = "vk_matmul",
    main = "src/main.zig",
    srcs = [
        "src/vulkan_loader.zig",
    ],
    deps = [
        "//shaders:matmul_coop_bf16_opt_spv_words",
        "//shaders:matmul_coop_bf16_spv_words",
        "//shaders:matmul_coop_f16_opt_spv_words",
        "//shaders:matmul_coop_f16_spv_words",
        "//shaders:matmul_nvcoop2_bf16_spv_words",
        "//shaders:matmul_nvcoop2_f16_spv_words",
        "//shaders:matmul_zig_spv_words",
    ],
    zigopts = [
        "-fllvm",
        "-lc",
    ],
    visibility = ["//visibility:public"],
)
