load("@rules_zig//zig:defs.bzl", "zig_binary", "zig_library")

genrule(
    name = "vulkan_zig_binding",
    srcs = ["@vulkan_headers//:registry/vk.xml"],
    outs = ["vk.zig"],
    cmd = "$(execpath @vulkan_zig//:vulkan_zig_generator) $(location @vulkan_headers//:registry/vk.xml) $@",
    tools = ["@vulkan_zig//:vulkan_zig_generator"],
)

zig_library(
    name = "vulkan",
    import_name = "vulkan",
    main = ":vulkan_zig_binding",
    visibility = ["//visibility:public"],
)

zig_binary(
    name = "vk_matmul",
    main = "src/main.zig",
    deps = [
        ":vulkan",
        "//shaders:matmul_coop_bf16_opt_spv_words",
        "//shaders:matmul_coop_bf16_spv_words",
        "//shaders:matmul_coop_f16_opt_spv_words",
        "//shaders:matmul_coop_f16_spv_words",
        "//shaders:matmul_coop_shared_f16_spv_words",
        "//shaders:matmul_nvcoop2_bf16_spv_words",
        "//shaders:matmul_nvcoop2_f16_spv_words",
        "//shaders:matmul_nvcoop2_square_f16_spv_words",
        "//shaders:matmul_nvcoop2_wide_f16_spv_words",
        "//shaders:matmul_zig_spv_words",
    ],
    zigopts = [
        "-fllvm",
        "-lc",
    ],
    visibility = ["//visibility:public"],
)

zig_binary(
    name = "vk_matmul_slang",
    main = "src/main.zig",
    deps = [
        ":vulkan",
        "//shaders:matmul_coop_bf16_opt_spv_words",
        "//shaders:matmul_coop_bf16_spv_words",
        "//shaders:matmul_coop_f16_opt_spv_words",
        "//shaders:matmul_coop_f16_spv_words",
        "//shaders:matmul_coop_shared_f16_spv_words",
        "//shaders:matmul_nvcoop2_bf16_spv_words",
        "//shaders:matmul_nvcoop2_f16_spv_words",
        "//shaders:matmul_nvcoop2_square_f16_slang_spv_words",
        "//shaders:matmul_nvcoop2_wide_f16_spv_words",
        "//shaders:matmul_zig_spv_words",
    ],
    zigopts = [
        "-fllvm",
        "-lc",
    ],
    visibility = ["//visibility:public"],
)

zig_binary(
    name = "vk_matmul_dsl",
    main = "src/main_dsl.zig",
    deps = [
        ":vulkan",
        "//shaders:matmul_coop_bf16_opt_spv_words",
        "//shaders:matmul_coop_bf16_spv_words",
        "//shaders:matmul_coop_f16_opt_dsl_text_spv_words",
        "//shaders:matmul_coop_f16_spv_words",
        "//shaders:matmul_coop_shared_f16_spv_words",
        "//shaders:matmul_nvcoop2_bf16_spv_words",
        "//shaders:matmul_nvcoop2_f16_spv_words",
        "//shaders:matmul_nvcoop2_square_f16_frontend_spv_words",
        "//shaders:matmul_nvcoop2_square_f16_dsl_text_spv_words",
        "//shaders:matmul_nvcoop2_wide_f16_spv_words",
        "//shaders:matmul_zig_dsl_spv_words",
    ],
    zigopts = [
        "-fllvm",
        "-lc",
    ],
    visibility = ["//visibility:public"],
)
